export const happySearch = {
  "albums": {
    "href": "https://api.spotify.com/v1/search?query=happy&type=album&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=0&limit=5",
    "items": [
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6pe92iYUnYByNR6uMcfZ4V"
            },
            "href": "https://api.spotify.com/v1/artists/6pe92iYUnYByNR6uMcfZ4V",
            "id": "6pe92iYUnYByNR6uMcfZ4V",
            "name": "emma",
            "type": "artist",
            "uri": "spotify:artist:6pe92iYUnYByNR6uMcfZ4V"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/7GetLDIDJeKtQi3oEbutx0"
        },
        "href": "https://api.spotify.com/v1/albums/7GetLDIDJeKtQi3oEbutx0",
        "id": "7GetLDIDJeKtQi3oEbutx0",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273b7b44a250ac6638b8164429d",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02b7b44a250ac6638b8164429d",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851b7b44a250ac6638b8164429d",
            "width": 64
          }
        ],
        "name": "Happy",
        "release_date": "2019-03-22",
        "release_date_precision": "day",
        "total_tracks": 2,
        "type": "album",
        "uri": "spotify:album:7GetLDIDJeKtQi3oEbutx0"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6Xk5Q0Njhbn2DVf3qOR1HD"
            },
            "href": "https://api.spotify.com/v1/artists/6Xk5Q0Njhbn2DVf3qOR1HD",
            "id": "6Xk5Q0Njhbn2DVf3qOR1HD",
            "name": "NSET",
            "type": "artist",
            "uri": "spotify:artist:6Xk5Q0Njhbn2DVf3qOR1HD"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/1GqPU5gm7hNVLVQbLtXH4t"
        },
        "href": "https://api.spotify.com/v1/albums/1GqPU5gm7hNVLVQbLtXH4t",
        "id": "1GqPU5gm7hNVLVQbLtXH4t",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b27378ce2440757531ea925dbc95",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e0278ce2440757531ea925dbc95",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d0000485178ce2440757531ea925dbc95",
            "width": 64
          }
        ],
        "name": "Happy",
        "release_date": "2023-12-24",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:1GqPU5gm7hNVLVQbLtXH4t"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0p3tzEAt0XWrBqbrwBoN1I"
            },
            "href": "https://api.spotify.com/v1/artists/0p3tzEAt0XWrBqbrwBoN1I",
            "id": "0p3tzEAt0XWrBqbrwBoN1I",
            "name": "Kyle Hume",
            "type": "artist",
            "uri": "spotify:artist:0p3tzEAt0XWrBqbrwBoN1I"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/5vkTIncsqYZfSof8ys9ae9"
        },
        "href": "https://api.spotify.com/v1/albums/5vkTIncsqYZfSof8ys9ae9",
        "id": "5vkTIncsqYZfSof8ys9ae9",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b27389cbfce249d7c4f7685e1be7",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e0289cbfce249d7c4f7685e1be7",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d0000485189cbfce249d7c4f7685e1be7",
            "width": 64
          }
        ],
        "name": "Happy",
        "release_date": "2023-05-26",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:5vkTIncsqYZfSof8ys9ae9"
      },
      {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5jUF0vJTYlZ6zGKnS9WK7v"
            },
            "href": "https://api.spotify.com/v1/artists/5jUF0vJTYlZ6zGKnS9WK7v",
            "id": "5jUF0vJTYlZ6zGKnS9WK7v",
            "name": "Kiik",
            "type": "artist",
            "uri": "spotify:artist:5jUF0vJTYlZ6zGKnS9WK7v"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4TgmvcUJcegf2THVSN55VJ"
            },
            "href": "https://api.spotify.com/v1/artists/4TgmvcUJcegf2THVSN55VJ",
            "id": "4TgmvcUJcegf2THVSN55VJ",
            "name": "Shin Giwon Paino",
            "type": "artist",
            "uri": "spotify:artist:4TgmvcUJcegf2THVSN55VJ"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/74qq22zPFjHJgxHH9AFuee"
        },
        "href": "https://api.spotify.com/v1/albums/74qq22zPFjHJgxHH9AFuee",
        "id": "74qq22zPFjHJgxHH9AFuee",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b2730a2450e42f45f5f44be577be",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e020a2450e42f45f5f44be577be",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d000048510a2450e42f45f5f44be577be",
            "width": 64
          }
        ],
        "name": "HAPPY",
        "release_date": "2024-11-11",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:74qq22zPFjHJgxHH9AFuee"
      },
      {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm"
            },
            "href": "https://api.spotify.com/v1/artists/5ksRONqssB7BR161NTtJAm",
            "id": "5ksRONqssB7BR161NTtJAm",
            "name": "Ace of Base",
            "type": "artist",
            "uri": "spotify:artist:5ksRONqssB7BR161NTtJAm"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/6cpOIdpPfGaazHsh5eYz0k"
        },
        "href": "https://api.spotify.com/v1/albums/6cpOIdpPfGaazHsh5eYz0k",
        "id": "6cpOIdpPfGaazHsh5eYz0k",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273b8e072ca95df6dc435b1484f",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02b8e072ca95df6dc435b1484f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851b8e072ca95df6dc435b1484f",
            "width": 64
          }
        ],
        "name": "Happy Nation",
        "release_date": "1992-11-16",
        "release_date_precision": "day",
        "total_tracks": 14,
        "type": "album",
        "uri": "spotify:album:6cpOIdpPfGaazHsh5eYz0k"
      }
    ],
    "limit": 5,
    "next": "https://api.spotify.com/v1/search?query=happy&type=album&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=5&limit=5",
    "offset": 0,
    "previous": null,
    "total": 105
  },
  "artists": {
    "href": "https://api.spotify.com/v1/search?query=happy&type=artist&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=0&limit=5",
    "items": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/5423rMdVbchY2cgu0GgH5X"
        },
        "followers": {
          "href": null,
          "total": 4941102
        },
        "genres": [
          "dangdut koplo",
          "javanese dangdut",
          "lagu jawa"
        ],
        "href": "https://api.spotify.com/v1/artists/5423rMdVbchY2cgu0GgH5X",
        "id": "5423rMdVbchY2cgu0GgH5X",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab6761610000e5eb862cb8a32659c4e651bb318a",
            "width": 640
          },
          {
            "height": 320,
            "url": "https://i.scdn.co/image/ab67616100005174862cb8a32659c4e651bb318a",
            "width": 320
          },
          {
            "height": 160,
            "url": "https://i.scdn.co/image/ab6761610000f178862cb8a32659c4e651bb318a",
            "width": 160
          }
        ],
        "name": "Happy Asmara",
        "popularity": 62,
        "type": "artist",
        "uri": "spotify:artist:5423rMdVbchY2cgu0GgH5X"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/3sLF4v5ZBIuK4WxQO6IZGY"
        },
        "followers": {
          "href": null,
          "total": 61
        },
        "genres": [],
        "href": "https://api.spotify.com/v1/artists/3sLF4v5ZBIuK4WxQO6IZGY",
        "id": "3sLF4v5ZBIuK4WxQO6IZGY",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab6761610000e5eba3d1ac7df8d78eb489586894",
            "width": 640
          },
          {
            "height": 320,
            "url": "https://i.scdn.co/image/ab67616100005174a3d1ac7df8d78eb489586894",
            "width": 320
          },
          {
            "height": 160,
            "url": "https://i.scdn.co/image/ab6761610000f178a3d1ac7df8d78eb489586894",
            "width": 160
          }
        ],
        "name": "Happy",
        "popularity": 3,
        "type": "artist",
        "uri": "spotify:artist:3sLF4v5ZBIuK4WxQO6IZGY"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/339DNkQkuhHKEcHw6oK8f0"
        },
        "followers": {
          "href": null,
          "total": 420809
        },
        "genres": [
          "britpop",
          "dance rock",
          "madchester"
        ],
        "href": "https://api.spotify.com/v1/artists/339DNkQkuhHKEcHw6oK8f0",
        "id": "339DNkQkuhHKEcHw6oK8f0",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab6761610000e5ebcc97b5500db463902db72582",
            "width": 640
          },
          {
            "height": 320,
            "url": "https://i.scdn.co/image/ab67616100005174cc97b5500db463902db72582",
            "width": 320
          },
          {
            "height": 160,
            "url": "https://i.scdn.co/image/ab6761610000f178cc97b5500db463902db72582",
            "width": 160
          }
        ],
        "name": "Happy Mondays",
        "popularity": 48,
        "type": "artist",
        "uri": "spotify:artist:339DNkQkuhHKEcHw6oK8f0"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/3nP6BTvc6mtLy0aOEVWVT8"
        },
        "followers": {
          "href": null,
          "total": 43
        },
        "genres": [],
        "href": "https://api.spotify.com/v1/artists/3nP6BTvc6mtLy0aOEVWVT8",
        "id": "3nP6BTvc6mtLy0aOEVWVT8",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab6761610000e5eb820deb3dbc28222b8a5fc249",
            "width": 640
          },
          {
            "height": 320,
            "url": "https://i.scdn.co/image/ab67616100005174820deb3dbc28222b8a5fc249",
            "width": 320
          },
          {
            "height": 160,
            "url": "https://i.scdn.co/image/ab6761610000f178820deb3dbc28222b8a5fc249",
            "width": 160
          }
        ],
        "name": "Happyjr",
        "popularity": 23,
        "type": "artist",
        "uri": "spotify:artist:3nP6BTvc6mtLy0aOEVWVT8"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0wCS5K5gJVAuAmVglBhXbe"
        },
        "followers": {
          "href": null,
          "total": 1134
        },
        "genres": [],
        "href": "https://api.spotify.com/v1/artists/0wCS5K5gJVAuAmVglBhXbe",
        "id": "0wCS5K5gJVAuAmVglBhXbe",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab6761610000e5ebe4813a155e3b06a4a7c2af69",
            "width": 640
          },
          {
            "height": 320,
            "url": "https://i.scdn.co/image/ab67616100005174e4813a155e3b06a4a7c2af69",
            "width": 320
          },
          {
            "height": 160,
            "url": "https://i.scdn.co/image/ab6761610000f178e4813a155e3b06a4a7c2af69",
            "width": 160
          }
        ],
        "name": "Happy",
        "popularity": 22,
        "type": "artist",
        "uri": "spotify:artist:0wCS5K5gJVAuAmVglBhXbe"
      }
    ],
    "limit": 5,
    "next": "https://api.spotify.com/v1/search?query=happy&type=artist&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=5&limit=5",
    "offset": 0,
    "previous": null,
    "total": 105
  },
  "tracks": {
    "href": "https://api.spotify.com/v1/search?query=happy&type=track&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=0&limit=5",
    "items": [
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6Xb4ezwoAQC4516kI89nWz"
              },
              "href": "https://api.spotify.com/v1/artists/6Xb4ezwoAQC4516kI89nWz",
              "id": "6Xb4ezwoAQC4516kI89nWz",
              "name": "Imogen Heap",
              "type": "artist",
              "uri": "spotify:artist:6Xb4ezwoAQC4516kI89nWz"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4JmrIJbpHWHZxOJg4awGh4"
          },
          "href": "https://api.spotify.com/v1/albums/4JmrIJbpHWHZxOJg4awGh4",
          "id": "4JmrIJbpHWHZxOJg4awGh4",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273ca7cad7b1dd4996d643433ef",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02ca7cad7b1dd4996d643433ef",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851ca7cad7b1dd4996d643433ef",
              "width": 64
            }
          ],
          "name": "The Happy Song",
          "release_date": "2016-10-17",
          "release_date_precision": "day",
          "total_tracks": 2,
          "type": "album",
          "uri": "spotify:album:4JmrIJbpHWHZxOJg4awGh4"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6Xb4ezwoAQC4516kI89nWz"
            },
            "href": "https://api.spotify.com/v1/artists/6Xb4ezwoAQC4516kI89nWz",
            "id": "6Xb4ezwoAQC4516kI89nWz",
            "name": "Imogen Heap",
            "type": "artist",
            "uri": "spotify:artist:6Xb4ezwoAQC4516kI89nWz"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 157924,
        "explicit": false,
        "external_ids": {
          "isrc": "SE5BU1601156"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6snoOAATGyud5oaIT9gwws"
        },
        "href": "https://api.spotify.com/v1/tracks/6snoOAATGyud5oaIT9gwws",
        "id": "6snoOAATGyud5oaIT9gwws",
        "is_local": false,
        "name": "The Happy Song",
        "popularity": 72,
        "preview_url": "https://p.scdn.co/mp3-preview/31ec10fa706fb70520ea6b530482befe357dc7c9?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6snoOAATGyud5oaIT9gwws"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8"
              },
              "href": "https://api.spotify.com/v1/artists/2RdwBSPQiwcmiDo9kixcl8",
              "id": "2RdwBSPQiwcmiDo9kixcl8",
              "name": "Pharrell Williams",
              "type": "artist",
              "uri": "spotify:artist:2RdwBSPQiwcmiDo9kixcl8"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0lrmy4pJINsFzycJvttX2W"
          },
          "href": "https://api.spotify.com/v1/albums/0lrmy4pJINsFzycJvttX2W",
          "id": "0lrmy4pJINsFzycJvttX2W",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273e8107e6d9214baa81bb79bba",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02e8107e6d9214baa81bb79bba",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851e8107e6d9214baa81bb79bba",
              "width": 64
            }
          ],
          "name": "G I R L",
          "release_date": "2014-03-03",
          "release_date_precision": "day",
          "total_tracks": 11,
          "type": "album",
          "uri": "spotify:album:0lrmy4pJINsFzycJvttX2W"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8"
            },
            "href": "https://api.spotify.com/v1/artists/2RdwBSPQiwcmiDo9kixcl8",
            "id": "2RdwBSPQiwcmiDo9kixcl8",
            "name": "Pharrell Williams",
            "type": "artist",
            "uri": "spotify:artist:2RdwBSPQiwcmiDo9kixcl8"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 232720,
        "explicit": false,
        "external_ids": {
          "isrc": "USQ4E1300686"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH"
        },
        "href": "https://api.spotify.com/v1/tracks/60nZcImufyMA1MKQY3dcCH",
        "id": "60nZcImufyMA1MKQY3dcCH",
        "is_local": false,
        "name": "Happy - From \"Despicable Me 2\"",
        "popularity": 79,
        "preview_url": "https://p.scdn.co/mp3-preview/5e0c8e5d899dea532d697fb20a851450e9614cfc?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 5,
        "type": "track",
        "uri": "spotify:track:60nZcImufyMA1MKQY3dcCH"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4yjDVfayc6bIBLuyDWuw5W"
              },
              "href": "https://api.spotify.com/v1/artists/4yjDVfayc6bIBLuyDWuw5W",
              "id": "4yjDVfayc6bIBLuyDWuw5W",
              "name": "Happy Birthday Songs",
              "type": "artist",
              "uri": "spotify:artist:4yjDVfayc6bIBLuyDWuw5W"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5DmODIhLV274RNBPrhwLYo"
          },
          "href": "https://api.spotify.com/v1/albums/5DmODIhLV274RNBPrhwLYo",
          "id": "5DmODIhLV274RNBPrhwLYo",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2734838420464683f253cd67b57",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e024838420464683f253cd67b57",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048514838420464683f253cd67b57",
              "width": 64
            }
          ],
          "name": "Happy Birthday To You - Best Playlist of Happy Birthday Songs, Vol. 1",
          "release_date": "2021-02-12",
          "release_date_precision": "day",
          "total_tracks": 20,
          "type": "album",
          "uri": "spotify:album:5DmODIhLV274RNBPrhwLYo"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4yjDVfayc6bIBLuyDWuw5W"
            },
            "href": "https://api.spotify.com/v1/artists/4yjDVfayc6bIBLuyDWuw5W",
            "id": "4yjDVfayc6bIBLuyDWuw5W",
            "name": "Happy Birthday Songs",
            "type": "artist",
            "uri": "spotify:artist:4yjDVfayc6bIBLuyDWuw5W"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 33215,
        "explicit": false,
        "external_ids": {
          "isrc": "USCNJ2100318"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2pW5kNCx133MWWirxegvng"
        },
        "href": "https://api.spotify.com/v1/tracks/2pW5kNCx133MWWirxegvng",
        "id": "2pW5kNCx133MWWirxegvng",
        "is_local": false,
        "name": "Happy Birthday To You - Classic Version",
        "popularity": 46,
        "preview_url": "https://p.scdn.co/mp3-preview/99408a443267912b5a26d29f57bee3d90d0ae0cb?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 18,
        "type": "track",
        "uri": "spotify:track:2pW5kNCx133MWWirxegvng"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/40XVsFgLf7yGKaC6Yiu7ff"
              },
              "href": "https://api.spotify.com/v1/artists/40XVsFgLf7yGKaC6Yiu7ff",
              "id": "40XVsFgLf7yGKaC6Yiu7ff",
              "name": "Happy Birthday TA",
              "type": "artist",
              "uri": "spotify:artist:40XVsFgLf7yGKaC6Yiu7ff"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4POPMvpDC7yGtZZ1agfhT0"
              },
              "href": "https://api.spotify.com/v1/artists/4POPMvpDC7yGtZZ1agfhT0",
              "id": "4POPMvpDC7yGtZZ1agfhT0",
              "name": "Torsten Abrolat",
              "type": "artist",
              "uri": "spotify:artist:4POPMvpDC7yGtZZ1agfhT0"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6IM07MmswhpROHB38CDrAy"
              },
              "href": "https://api.spotify.com/v1/artists/6IM07MmswhpROHB38CDrAy",
              "id": "6IM07MmswhpROHB38CDrAy",
              "name": "Toddi Spieluhr",
              "type": "artist",
              "uri": "spotify:artist:6IM07MmswhpROHB38CDrAy"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1tsOX4t0qRI00QXS84v1vW"
          },
          "href": "https://api.spotify.com/v1/albums/1tsOX4t0qRI00QXS84v1vW",
          "id": "1tsOX4t0qRI00QXS84v1vW",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730cc8b8a3fcd0cd9d284ca105",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020cc8b8a3fcd0cd9d284ca105",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510cc8b8a3fcd0cd9d284ca105",
              "width": 64
            }
          ],
          "name": "Happy Birthday to You! Songs & Lieder zum Geburtstag, Geburtstagslieder",
          "release_date": "2018-05-17",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:1tsOX4t0qRI00QXS84v1vW"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/40XVsFgLf7yGKaC6Yiu7ff"
            },
            "href": "https://api.spotify.com/v1/artists/40XVsFgLf7yGKaC6Yiu7ff",
            "id": "40XVsFgLf7yGKaC6Yiu7ff",
            "name": "Happy Birthday TA",
            "type": "artist",
            "uri": "spotify:artist:40XVsFgLf7yGKaC6Yiu7ff"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4POPMvpDC7yGtZZ1agfhT0"
            },
            "href": "https://api.spotify.com/v1/artists/4POPMvpDC7yGtZZ1agfhT0",
            "id": "4POPMvpDC7yGtZZ1agfhT0",
            "name": "Torsten Abrolat",
            "type": "artist",
            "uri": "spotify:artist:4POPMvpDC7yGtZZ1agfhT0"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 44269,
        "explicit": false,
        "external_ids": {
          "isrc": "DELD90805971"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6lNTl7eExy6VS8rnD3O8re"
        },
        "href": "https://api.spotify.com/v1/tracks/6lNTl7eExy6VS8rnD3O8re",
        "id": "6lNTl7eExy6VS8rnD3O8re",
        "is_local": false,
        "name": "Happy Birthday to You",
        "popularity": 44,
        "preview_url": "https://p.scdn.co/mp3-preview/79751a09073f1fa8a6e206dd00f98c9d9dd10df9?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6lNTl7eExy6VS8rnD3O8re"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm"
              },
              "href": "https://api.spotify.com/v1/artists/5ksRONqssB7BR161NTtJAm",
              "id": "5ksRONqssB7BR161NTtJAm",
              "name": "Ace of Base",
              "type": "artist",
              "uri": "spotify:artist:5ksRONqssB7BR161NTtJAm"
            }
          ],
          "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6cpOIdpPfGaazHsh5eYz0k"
          },
          "href": "https://api.spotify.com/v1/albums/6cpOIdpPfGaazHsh5eYz0k",
          "id": "6cpOIdpPfGaazHsh5eYz0k",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273b8e072ca95df6dc435b1484f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02b8e072ca95df6dc435b1484f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851b8e072ca95df6dc435b1484f",
              "width": 64
            }
          ],
          "name": "Happy Nation",
          "release_date": "1992-11-16",
          "release_date_precision": "day",
          "total_tracks": 14,
          "type": "album",
          "uri": "spotify:album:6cpOIdpPfGaazHsh5eYz0k"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm"
            },
            "href": "https://api.spotify.com/v1/artists/5ksRONqssB7BR161NTtJAm",
            "id": "5ksRONqssB7BR161NTtJAm",
            "name": "Ace of Base",
            "type": "artist",
            "uri": "spotify:artist:5ksRONqssB7BR161NTtJAm"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "disc_number": 1,
        "duration_ms": 255413,
        "explicit": false,
        "external_ids": {
          "isrc": "SEVJH0803407"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7yCF65vpc7sUwPjftI0iFb"
        },
        "href": "https://api.spotify.com/v1/tracks/7yCF65vpc7sUwPjftI0iFb",
        "id": "7yCF65vpc7sUwPjftI0iFb",
        "is_local": false,
        "name": "Happy Nation",
        "popularity": 72,
        "preview_url": "https://p.scdn.co/mp3-preview/cb305ced36ceac1cae575c03f7d371f5dc030002?cid=cfe923b2d660439caf2b557b21f31221",
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:7yCF65vpc7sUwPjftI0iFb"
      }
    ],
    "limit": 5,
    "next": "https://api.spotify.com/v1/search?query=happy&type=track&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=5&limit=5",
    "offset": 0,
    "previous": null,
    "total": 102
  },
  "playlists": {
    "href": "https://api.spotify.com/v1/search?query=happy&type=playlist&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=0&limit=5",
    "items": [
      {
        "collaborative": false,
        "description": "",
        "external_urls": {
          "spotify": "https://open.spotify.com/playlist/5UgG3XS8q1lgsnHqRi6Qle"
        },
        "href": "https://api.spotify.com/v1/playlists/5UgG3XS8q1lgsnHqRi6Qle",
        "id": "5UgG3XS8q1lgsnHqRi6Qle",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273e8107e6d9214baa81bb79bba",
            "width": 640
          }
        ],
        "name": "Pharrell Williams - Happy",
        "owner": {
          "display_name": "21fekud673fjaadpmzncljq2a",
          "external_urls": {
            "spotify": "https://open.spotify.com/user/21fekud673fjaadpmzncljq2a"
          },
          "href": "https://api.spotify.com/v1/users/21fekud673fjaadpmzncljq2a",
          "id": "21fekud673fjaadpmzncljq2a",
          "type": "user",
          "uri": "spotify:user:21fekud673fjaadpmzncljq2a"
        },
        "primary_color": null,
        "public": null,
        "snapshot_id": "NCwxYzA5YWI3ZWU2MjIwZjgxN2ExNzUxZTQxYWQzMDFiMGNjNGRlNTUw",
        "tracks": {
          "href": "https://api.spotify.com/v1/playlists/5UgG3XS8q1lgsnHqRi6Qle/tracks",
          "total": 2
        },
        "type": "playlist",
        "uri": "spotify:playlist:5UgG3XS8q1lgsnHqRi6Qle"
      },
      {
        "collaborative": false,
        "description": "Hits to boost your mood and fill you with happiness!",
        "external_urls": {
          "spotify": "https://open.spotify.com/playlist/37i9dQZF1DXdPec7aLTmlC"
        },
        "href": "https://api.spotify.com/v1/playlists/37i9dQZF1DXdPec7aLTmlC",
        "id": "37i9dQZF1DXdPec7aLTmlC",
        "images": [
          {
            "height": null,
            "url": "https://i.scdn.co/image/ab67706f00000003a46ea55285180036c5e8f196",
            "width": null
          }
        ],
        "name": "Happy Hits!",
        "owner": {
          "display_name": "Spotify",
          "external_urls": {
            "spotify": "https://open.spotify.com/user/spotify"
          },
          "href": "https://api.spotify.com/v1/users/spotify",
          "id": "spotify",
          "type": "user",
          "uri": "spotify:user:spotify"
        },
        "primary_color": null,
        "public": null,
        "snapshot_id": "MTcxODMxNjAwMCwwMDAwMDAwMDlmMzVmMzM0NWMwYTI0ZTI3NGExMWM0NTViYTdjYzVm",
        "tracks": {
          "href": "https://api.spotify.com/v1/playlists/37i9dQZF1DXdPec7aLTmlC/tracks",
          "total": 100
        },
        "type": "playlist",
        "uri": "spotify:playlist:37i9dQZF1DXdPec7aLTmlC"
      },
      {
        "collaborative": false,
        "description": "<a href=spotify:playlist:37i9dQZF1EIVJHRLofMWOn>Monali Thakur</a>, <a href=spotify:playlist:37i9dQZF1EIUy4oR9HDQOj>DJ Genki</a>, <a href=spotify:playlist:37i9dQZF1EIYdka1jtOSvd>Yasser Desai</a> and more",
        "external_urls": {
          "spotify": "https://open.spotify.com/playlist/37i9dQZF1EVJSvZp5AOML2"
        },
        "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EVJSvZp5AOML2",
        "id": "37i9dQZF1EVJSvZp5AOML2",
        "images": [
          {
            "height": null,
            "url": "https://seed-mix-image.spotifycdn.com/v6/img/happy/2o4R2rK7FetH40HTv0SUWl/en-GB/large",
            "width": null
          }
        ],
        "name": "Happy Mix",
        "owner": {
          "display_name": "Spotify",
          "external_urls": {
            "spotify": "https://open.spotify.com/user/spotify"
          },
          "href": "https://api.spotify.com/v1/users/spotify",
          "id": "spotify",
          "type": "user",
          "uri": "spotify:user:spotify"
        },
        "primary_color": null,
        "public": null,
        "snapshot_id": "MCwwMDAwMDAwMDA4ZTg1MmI3NDFhMTQ3NGVmMmExOTQ2OWU1NDFiZWY5",
        "tracks": {
          "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EVJSvZp5AOML2/tracks",
          "total": 50
        },
        "type": "playlist",
        "uri": "spotify:playlist:37i9dQZF1EVJSvZp5AOML2"
      },
      {
        "collaborative": false,
        "description": "Energetic Happy music picked just for you",
        "external_urls": {
          "spotify": "https://open.spotify.com/playlist/37i9dQZF1EIeEZPgsd7pko"
        },
        "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EIeEZPgsd7pko",
        "id": "37i9dQZF1EIeEZPgsd7pko",
        "images": [
          {
            "height": null,
            "url": "https://seed-mix-image.spotifycdn.com/v6/img/desc/Energetic%20Happy/en/large",
            "width": null
          }
        ],
        "name": "Energetic Happy Mix",
        "owner": {
          "display_name": "Spotify",
          "external_urls": {
            "spotify": "https://open.spotify.com/user/spotify"
          },
          "href": "https://api.spotify.com/v1/users/spotify",
          "id": "spotify",
          "type": "user",
          "uri": "spotify:user:spotify"
        },
        "primary_color": null,
        "public": null,
        "snapshot_id": "MCwwMDAwMDAwMGFkNDU4YmZhZDZiNWM0N2M4ZjdmNGMyZDRmZjQ4OTcy",
        "tracks": {
          "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EIeEZPgsd7pko/tracks",
          "total": 0
        },
        "type": "playlist",
        "uri": "spotify:playlist:37i9dQZF1EIeEZPgsd7pko"
      },
      {
        "collaborative": false,
        "description": "Good Mood Happy music picked just for you",
        "external_urls": {
          "spotify": "https://open.spotify.com/playlist/37i9dQZF1EIgNoWOvbnUCk"
        },
        "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EIgNoWOvbnUCk",
        "id": "37i9dQZF1EIgNoWOvbnUCk",
        "images": [
          {
            "height": null,
            "url": "https://seed-mix-image.spotifycdn.com/v6/img/desc/Good%20Mood%20Happy/en/large",
            "width": null
          }
        ],
        "name": "Good Mood Happy Mix",
        "owner": {
          "display_name": "Spotify",
          "external_urls": {
            "spotify": "https://open.spotify.com/user/spotify"
          },
          "href": "https://api.spotify.com/v1/users/spotify",
          "id": "spotify",
          "type": "user",
          "uri": "spotify:user:spotify"
        },
        "primary_color": null,
        "public": null,
        "snapshot_id": "MCwwMDAwMDAwMDNiMTcyNTE0OGZlMDNjMGJjNTFjNTViNjFiMDM4MzYz",
        "tracks": {
          "href": "https://api.spotify.com/v1/playlists/37i9dQZF1EIgNoWOvbnUCk/tracks",
          "total": 0
        },
        "type": "playlist",
        "uri": "spotify:playlist:37i9dQZF1EIgNoWOvbnUCk"
      }
    ],
    "limit": 5,
    "next": "https://api.spotify.com/v1/search?query=happy&type=playlist&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=5&limit=5",
    "offset": 0,
    "previous": null,
    "total": 1000
  }
}